### ISSUE TITLE
Network option

### ISSUE THREAD

**Issue by reionwong** [cyberos/cyber-settings#10]

**Comment by itsvic-dev** [comment]
I suggest going with NetworkManager for the long run, though it might be hard to control over D-Bus.

**Comment by reionwong** [comment]
Yes, I'm also using network manager

**Comment by itsvic-dev** [comment]
I think [this KDE library](https://api.kde.org/frameworks/networkmanager-qt/html/index.html) will help us out.

**Comment by reionwong** [comment]
I plan to use NetworkManagerQt to manage the network.
