### ISSUE TITLE
Fixed font always resets to the default option in the Appearance page.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#11]
The fixed font option always resets itself to the 1st option (which is Twemoji for me for some bizarre reason), despite setting it to JetBrains Mono.

![image](https://user-images.githubusercontent.com/17727163/102093576-9a63b280-3e21-11eb-9e0d-01e0d4bcbad4.png)

Any idea why? @rekols

**Comment by reionwong** [comment]
~~The reason is that it obtains the default Fixed Font from QFontDatabase::systemFont(), it is not updated when the Fixed Font is set. It should be obtained from the DBus Interface of Settings Daemon to be correct.~~

**Comment by itsvic-dev** [comment]
I believe it should be a quick patch to the `appearance.cpp` font handler, correct?

**Comment by reionwong** [comment]
![Screenshot from 2020-12-14 23-05-07](https://user-images.githubusercontent.com/9636382/102097440-dbc78280-3e60-11eb-8ac1-b9e00ec81f73.png)

I have fixed it and I am pushing

**Comment by reionwong** [comment]
It's not a problem with QFontDatabase::systemFont()

**Comment by itsvic-dev** [comment]
Yup, fixed. Closing.

**Comment by itsvic-dev** [comment]
![image](https://user-images.githubusercontent.com/17727163/102098303-52478e80-3e27-11eb-81bd-6ce144933d35.png)
