### ISSUE TITLE
Resolution settings

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#13]
Currently Cyber doesn't really like being resized at runtime.

![image](https://user-images.githubusercontent.com/17727163/102204785-9344af00-3eca-11eb-9de0-eb3cb1ba9e1d.png)
(Cyber running in 1366x768 after being started in 1920x1080)

We should add settings to change the resolution and reposition/resize/restart the desktop daemon, status bar and dock.

**Comment by reionwong** [comment]
I will fix them.

**Comment by reionwong** [comment]
Dock has been fixed: https://github.com/cyberos/cyber-dock/commit/701b3096f4417f0143a9d7e014c5bf2d4829205a

**Comment by reionwong** [comment]
Statusbar: https://github.com/cyberos/cyber-statusbar/commit/2e65700d52cc255131eb67f7f606f545eceeb38a

**Comment by reionwong** [comment]
The desktop seems to be correct. U verify whether these problems are resolved. :)

**Comment by itsvic-dev** [comment]
The dock, statusbar, and desktop daemon don't adhere to the resolution changes when set with xrandr, but they do adhere to resolution changes over TigerVNC, weird.

**Comment by itsvic-dev** [comment]
Nevermind, they do now.

**Comment by itsvic-dev** [comment]
![image](https://user-images.githubusercontent.com/17727163/102349145-2fda8000-3fa3-11eb-9d05-d95ee17bb40c.png)

**Comment by reionwong** [comment]
There is still a problem on my laptop: After logging in to Cyber Desktop for the first time, adjusting the resolution, Dock and Statusbar, Desktop did not change.

**Comment by itsvic-dev** [comment]
For me it didn't adjust until resizing down, then back up, and back down.

**Comment by reionwong** [comment]
I've found a solution. I'm trying.

**Comment by reionwong** [comment]
Desktop: https://github.com/cyberos/cyber-workspace/commit/8df4f8535f9826b71dbadaf250f043ccfc806ca5
Dock: https://github.com/cyberos/cyber-dock/commit/cfa251fe7cead4c7d12e1411b3337d144279f558
Statusbar: https://github.com/cyberos/cyber-statusbar/commit/2e53d3831bd8b074ffcbf8c56e6444c5423379c4

**Comment by itsvic-dev** [comment]
Can you test it for me? I'm not on my laptop right now.

**Comment by reionwong** [comment]
Yes, It has been repaired.
