### ISSUE TITLE
Wi-Fi login prompt clips behind window

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#16]
![image](https://user-images.githubusercontent.com/17727163/102731221-8d6e2400-4337-11eb-8ba7-961e7a071653.png)

It'd be better to center the popup in the Settings window, and put the Wi-Fi network name onto the popup instead.

(Tip: in the commit message you can add "closes #?" instead of mentioning the issue)

**Comment by reionwong** [comment]
I've changed window dialog.
