### ISSUE TITLE
undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb

### ISSUE THREAD

**Issue by Z-bin** [cyberos/cyber-settings#18]
Development environment： Ubuntu 20.04.1 LTS
qt version: 5.15.2
Hello, I installed the development environment of qt5.15 through qt-unified-linux-x64-4.0.1-online.run.
But an error is reported:

`build-cyber-settings-unknown-Debug/cyber-settings: symbol lookup error: /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API`
How should I solve this problem？

----------update------------------
This error also occurred on cyber-fm

**Comment by itsvic-dev** [comment]
This looks like an issue with your installation of Qt 5, as suggested by `Qt_5_PRIVATE_API` at the end of your error string.

Nothing we can do to fix it, recompile Qt 5 and try again.

**Comment by Z-bin** [comment]
> This looks like an issue with your installation of Qt 5, as suggested by `Qt_5_PRIVATE_API` at the end of your error string.
> 
> Nothing we can do to fix it, recompile Qt 5 and try again.

Thanks, I will look for a solution

**Comment by Ruzhelovich-Vladimir** [comment]
Hello, 
i also got this error, trying to solve 2nd day
Ubuntu Mate System 20.04, Qt 5.12.8, pyqt5==5.15.4

symbol lookup error: /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API
