### ISSUE TITLE
Behavior on opacity in BackgroundPage.qml doesn't seem to work.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#20]
I don't know why it doesn't want to work. Could you guys help me? @rekols @Z-bin 

This should make it more clear, visually speaking:
![opacity](https://user-images.githubusercontent.com/17727163/104374190-cc9c2900-5521-11eb-91b8-174798df9df4.gif)

**Comment by reionwong** [comment]
I fixed it.

**Comment by reionwong** [comment]
```
                    onEntered: function() {
//before
                        parent.opacity = 0.7
// after
                        image.opacity = 0.7
                    }
```
