### ISSUE TITLE
Display module

### ISSUE THREAD

**Issue by Z-bin** [cyberos/cyber-settings#21]
Is there a plan to develop a display module? Including setting screen resolution, screen refresh rate, screen orientation and other general screen settings...

**Comment by reionwong** [comment]
Yep, in the plan.

**Comment by Z-bin** [comment]
> Yep, in the plan.

How can I participate in the development of the display？

**Comment by itsvic-dev** [comment]
You could start by introducing XRandr hooks maybe?

**Comment by itsvic-dev** [comment]
Idea: DBus hooks for XRandr. Something to implement in [cyber-workspace](https://github.com/cyberos/cyber-workspace)'s settings daemon.

**Comment by Z-bin** [comment]
> Idea: DBus hooks for XRandr. Something to implement in [cyber-workspace](https://github.com/cyberos/cyber-workspace)'s settings daemon.

Thank you, I will try my best.

**Comment by itsvic-dev** [comment]
@Z-bin @rekols This might help us as reference, if we want to go for XRandR: https://christian.amsuess.com/tools/arandr/

**Comment by liumartin** [comment]
https://github.com/cyberos/cyber-settings/commit/2e62979a0893819daeab312dbbe7c4e778fd35e6
