### ISSUE TITLE
Using header bar space

### ISSUE THREAD

**Issue by reionwong** [cyberos/cyber-settings#25]

**Comment by reionwong** [comment]
Original:

![2021-02-16 04-37-44屏幕截图](https://user-images.githubusercontent.com/9636382/107991082-d75e4800-7010-11eb-8dea-56be33ab905a.png)

Later:

![2021-02-16 04-38-11屏幕截图](https://user-images.githubusercontent.com/9636382/107991099-e218dd00-7010-11eb-8b52-d4e457031571.png)

How do you feel? @omaemae

**Comment by itsvic-dev** [comment]
Looks good. @rekols

**Comment by reionwong** [comment]
Allright
