### ISSUE TITLE
New Settings design

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#3]
Thought that the Settings lacked a nicer design, so I'm currently improving it.
# New design (preview)
## Light mode
![Light mode (preview)](https://user-images.githubusercontent.com/17727163/101935581-99dbd980-3bdf-11eb-97a9-b31dc4666a77.png)
## Dark mode
![Dark mode (preview)](https://user-images.githubusercontent.com/17727163/101935637-a8c28c00-3bdf-11eb-8e89-5182d6886c88.png)

# Old design
## Light mode
![Light mode (original)](https://user-images.githubusercontent.com/17727163/101935293-20dc8200-3bdf-11eb-9fd9-25ec2a5038be.png)
## Dark mode
![Dark mode (original)](https://user-images.githubusercontent.com/17727163/101935307-2934bd00-3bdf-11eb-83e0-f9232bdee10e.png)

# Which one is better?
Waiting for opinions and possible improvements!

**Comment by Patrosi73** [comment]
not gonna lie i think the new one is better, just because it fits well with the general color style

also, speaking of colors, why not add a settings option to change the general system color? would be neat.

**Comment by itsvic-dev** [comment]
Will look into the idea of changing the color scheme, thanks @Patrosi73!

**Comment by itsvic-dev** [comment]
Merged the new design so far, closing.

**Comment by reionwong** [comment]
pretty good, It will be better to add icons to Left SideBar in the future
