### ISSUE TITLE
Battery progress indicator exceeds bounds of background.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#4]
When the indicator is at a low percentage, it will exceed the bounds of the background (because the radius is smaller because of the shorter width). This image should make it a lot more clear:
![image](https://user-images.githubusercontent.com/17727163/101965206-1c7e8c00-3c14-11eb-9b8b-01c718fecb02.png)

To fix it, I assume that an invisible `Rectangle` object could be used with the correct radius, then remove the radius from the indicator and use the invisible Rectangle as a mask.

Could you try doing so? @rekols

**Comment by reionwong** [comment]
I've fixed it :)

![Screenshot from 2020-12-12 13-28-00](https://user-images.githubusercontent.com/9636382/101976220-02799380-3c7e-11eb-83b8-3f57866a3ba2.png)

![Screenshot from 2020-12-12 13-28-27](https://user-images.githubusercontent.com/9636382/101976223-060d1a80-3c7e-11eb-8095-48882e6fd040.png)
