### ISSUE TITLE
Dark Appearance Dims Wallpaper

### ISSUE THREAD

**Issue by reionwong** [cyberos/cyber-settings#7]

**Comment by itsvic-dev** [comment]
I don't really like the idea of dimming the wallpaper. It could be incorporated as a toggle for people who *do* want it, though!

**Comment by reionwong** [comment]
Yes, I made it controllable and turned off by default

**Comment by itsvic-dev** [comment]
:+1:

**Comment by reionwong** [comment]
https://github.com/cyberos/cyber-settings/commit/0941af3d02750f143e8daa546a81abeb236576b4

https://github.com/cyberos/cyber-workspace/commit/4be89b1b98347e17954bcdab0b5754329e527845
