### ISSUE TITLE
Accent colors in Appearance page

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-settings#9]
We added accent colors, now we need a way to show off the accent colors.
@rekols could you add accent colors to the Appearance page?

**Comment by reionwong** [comment]
YEP, I will refer to the design of macOS

<img width="780" alt="Screen Shot 2020-12-13 at 11 47 32 PM" src="https://user-images.githubusercontent.com/9636382/102020639-5cc94000-3db5-11eb-8af7-558aead908b0.png">

**Comment by itsvic-dev** [comment]
Did it just like my head imagined it, pushing to upstream soon.
![image](https://user-images.githubusercontent.com/17727163/102064271-6378a700-3df7-11eb-9191-d26f9202a658.png)

**Comment by reionwong** [comment]
GOOD JOB

**Comment by reionwong** [comment]
I think it would be better to move it under THEME :)

**Comment by itsvic-dev** [comment]
If you think it'll look better, then go for it.
